// <auto-generated />
namespace MusicStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class genrestables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genrestables));
        
        string IMigrationMetadata.Id
        {
            get { return "202211012155422_genres tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
